# Generated by Django 5.0.7 on 2024-08-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='memo',
            new_name='detile',
        ),
        migrations.AddField(
            model_name='todo',
            name='statu',
            field=models.TextField(blank=True, choices=[('Done', 'Done'), ('InProgress', 'InProgress')]),
        ),
    ]
