# Generated by Django 5.0.7 on 2024-08-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_memo_todo_detile_todo_statu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='statu',
            new_name='status',
        ),
    ]
